package book;
import java.io.*;
import javax.xml.parsers.*;
import javax.xml.stream.*;
import javax.xml.xpath.*;
import org.xml.sax.SAXException;

public class StAXBooks {

	public static void main(String[] args) throws IOException, XMLStreamException,ParserConfigurationException,
	SAXException, IOException, XPathExpressionException{
	       String fileName = "catalog2.xml";
	        FileWriter fileWriter = new FileWriter(fileName);  
	        XMLOutputFactory factory = XMLOutputFactory.newInstance();

	        XMLStreamWriter writer = factory.createXMLStreamWriter(fileWriter);
	        try {
		        writer.writeStartDocument();
			        writer.writeStartElement("Books");
				        writer.writeStartElement("Book");
					        writer.writeStartElement("autor");
					        writer.writeCharacters("Ivan Vazov");
					        writer.writeEndElement();
					        writer.writeStartElement("title");
					        writer.writeCharacters("Pod Igoto");
					        writer.writeEndElement();
					        writer.writeStartElement("isbn");
					        writer.writeCharacters("12Bn453");
					        writer.writeEndElement();
					        writer.writeStartElement("price");
					        writer.writeCharacters("15.25");
					        writer.writeEndElement();
					        writer.writeStartElement("publisher");
					        writer.writeCharacters("Helicon");
					        writer.writeEndElement();
				        writer.writeEndElement();
				        writer.writeStartElement("Book");
				        	writer.writeStartElement("autor");
				        	writer.writeCharacters("Terry Pratchet");
				        	writer.writeEndElement();
				        	writer.writeStartElement("title");
				        	writer.writeCharacters("Color of magic");
				        	writer.writeEndElement();
				        	writer.writeStartElement("isbn");
				        	writer.writeCharacters("110a23");
				        	writer.writeEndElement();
				        	writer.writeStartElement("price");
				        	writer.writeCharacters("10.0");
				        	writer.writeEndElement();
					        writer.writeStartElement("publisher");
					        writer.writeCharacters("Vuzev");
					        writer.writeEndElement();
				        writer.writeEndElement();
				        writer.writeStartElement("Book");
				        	writer.writeStartElement("autor");
				        	writer.writeCharacters("Terry Pratchet");
				        	writer.writeEndElement();
				        	writer.writeStartElement("title");
				        	writer.writeCharacters("Hog father");
				        	writer.writeEndElement();
				        	writer.writeStartElement("isbn");
				        	writer.writeCharacters("115sf324");
				        	writer.writeEndElement();
				        	writer.writeStartElement("price");
				        	writer.writeCharacters("12.0");
				        	writer.writeEndElement();
					        writer.writeStartElement("publisher");
					        writer.writeCharacters("Vuzev");
					        writer.writeEndElement();
					    writer.writeEndElement();
				        writer.writeStartElement("Book");
				        	writer.writeStartElement("autor");
				        	writer.writeCharacters("Terry Pratchet");
				        	writer.writeEndElement();
				        	writer.writeStartElement("title");
				        	writer.writeCharacters("Where is my cow");
				        	writer.writeEndElement();
				        	writer.writeStartElement("isbn");
				        	writer.writeCharacters("11er145");
				        	writer.writeEndElement();
				        	writer.writeStartElement("price");
				        	writer.writeCharacters("8.0");
				        	writer.writeEndElement();
					        writer.writeStartElement("publisher");
					        writer.writeCharacters("Vuzev");
					        writer.writeEndElement();
					    writer.writeEndElement();
				        writer.writeStartElement("Book");
				        	writer.writeStartElement("autor");
				        	writer.writeCharacters("Dan Brown");
				        	writer.writeEndElement();
				        	writer.writeStartElement("title");
				        	writer.writeCharacters("Angels and demons");
				        	writer.writeEndElement();
				        	writer.writeStartElement("isbn");
				        	writer.writeCharacters("110asF4sf");
				        	writer.writeEndElement();
				        	writer.writeStartElement("price");
				        	writer.writeCharacters("19.90");
				        	writer.writeEndElement();
					        writer.writeStartElement("publisher");
					        writer.writeCharacters("Bard");
					        writer.writeEndElement();
					    writer.writeEndElement();
				        writer.writeStartElement("Book");
				        	writer.writeStartElement("autor");
				        	writer.writeCharacters("J. R. Tolkin");
				        	writer.writeEndElement();
				        	writer.writeStartElement("title");
				        	writer.writeCharacters("The lord of the rings");
				        	writer.writeEndElement();
				        	writer.writeStartElement("isbn");
				        	writer.writeCharacters("110ae547");
				        	writer.writeEndElement();
				        	writer.writeStartElement("price");
				        	writer.writeCharacters("35.0");
				        	writer.writeEndElement();
					        writer.writeStartElement("publisher");
					        writer.writeCharacters("Bard");
					        writer.writeEndElement();
					    writer.writeEndElement();
					    writer.writeStartElement("Book");
				        	writer.writeStartElement("autor");
				        	writer.writeCharacters("George R. R. Martin");
				        	writer.writeEndElement();
				        	writer.writeStartElement("title");
				        	writer.writeCharacters("Song of fire and ice");
				        	writer.writeEndElement();
				        	writer.writeStartElement("isbn");
				        	writer.writeCharacters("12af87");
				        	writer.writeEndElement();
				        	writer.writeStartElement("price");
				        	writer.writeCharacters("27.50");
				        	writer.writeEndElement();
					        writer.writeStartElement("publisher");
					        writer.writeCharacters("Bard");
					        writer.writeEndElement();
					    writer.writeEndElement();
				        writer.writeStartElement("Book");
				        	writer.writeStartElement("autor");
				        	writer.writeCharacters("Agatha Christie");
				        	writer.writeEndElement();
				        	writer.writeStartElement("title");
				        	writer.writeCharacters("Murder on the orient express");
				        	writer.writeEndElement();
				        	writer.writeStartElement("isbn");
				        	writer.writeCharacters("110asdgs");
				        	writer.writeEndElement();
				        	writer.writeStartElement("price");
				        	writer.writeCharacters("9.99");
				        	writer.writeEndElement();
					        writer.writeStartElement("publisher");
					        writer.writeCharacters("Softpress");
					        writer.writeEndElement();
					   writer.writeEndElement();
					   writer.writeStartElement("Book");
				        	writer.writeStartElement("autor");
				        	writer.writeCharacters("JK Rowling");
				        	writer.writeEndElement();
				        	writer.writeStartElement("title");
				        	writer.writeCharacters("Harry Potter and the chamber of secrets");
				        	writer.writeEndElement();
				        	writer.writeStartElement("isbn");
				        	writer.writeCharacters("110a457");
				        	writer.writeEndElement();
				        	writer.writeStartElement("price");
				        	writer.writeCharacters("18.99");
				        	writer.writeEndElement();
					        writer.writeStartElement("publisher");
					        writer.writeCharacters("Softpress");
					        writer.writeEndElement();
					    writer.writeEndElement();
				        writer.writeStartElement("Book");
				        	writer.writeStartElement("autor");
				        	writer.writeCharacters("Steven Erikson");
				        	writer.writeEndElement();
				        	writer.writeStartElement("title");
				        	writer.writeCharacters("Malazan Book of the Fallen");
				        	writer.writeEndElement();
				        	writer.writeStartElement("isbn");
				        	writer.writeCharacters("110ahdh456");
				        	writer.writeEndElement();
				        	writer.writeStartElement("price");
				        	writer.writeCharacters("18.0");
				        	writer.writeEndElement();
					        writer.writeStartElement("publisher");
					        writer.writeCharacters("Bard");
					        writer.writeEndElement();
					    writer.writeEndElement();
			        writer.writeEndElement();
				writer.writeEndDocument();
		        writer.flush();
	        } finally {
	            writer.close();
	        }	
	}
}
