package view;

import controler.PlaneDBQueries;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Plane;
//Start Class DeleteJDialog
//Child on PlaneFrame Class (By Modal Link)
public class DeleteJDialog extends javax.swing.JDialog {
    //Class Fields.
    private Plane plane;
    private PlaneDBQueries planeQueries;

    //Class constructor
    public DeleteJDialog(PlaneFrame plainFrame, boolean modal, Plane plane, PlaneDBQueries planeQueries) {
        super(plainFrame, modal); //call JDialog constructor. Create Modal Link with PlaneFrame
        setPlane(plane); //Call Set method
        initComponents(); //Create GUI
        setPlaneQueries(planeQueries); //Call Set method
        setLocationRelativeTo(null); //set Location to center
    }//End constructor

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Delete Plane");
        setIconImage(new ImageIcon(getClass().getResource("/icons/deletePlane.png")).getImage());
        setResizable(false);

        jButton2.setText("No");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Yes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Number: " + this.plane.getPlaneID());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Help.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Do you want to delete this Plane?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //"No" Button Action Listener
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose(); //close UpdateFrame
    }//GEN-LAST:event_jButton2ActionPerformed

    //"Yes" Button Action Listener
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int result = 0;
        try {
            //call methos to exequte query
            result = this.planeQueries.removePlaneByID(getPlane().getPlaneID());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error! DataBase error call Admin!",
                    "DataBase Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
        //if - else statement. Show result from exequted query
        if (result != 0) {
            JOptionPane.showMessageDialog(this, "Your Plane was deleted from Plane DB!!!",
                    "Delete A Plane", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Your Plane can NOT be deleted!!!",
                    "Delete A Plane", JOptionPane.ERROR_MESSAGE);
        }//end if - else statement
        dispose(); //close UpdateDialog
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    //Setter for Plane
    private void setPlane(Plane plane) {
        this.plane = plane;
    }//end method

    //Getter for Plane
    public Plane getPlane() {
        return plane;
    }//end method

    //Setter for PlaneQueries
    private void setPlaneQueries(PlaneDBQueries planeQueries) {
        this.planeQueries = planeQueries;
    }//end method 
}//end Class DeleteJDialog
